#! /bin/bash

PROG_NAME=$(basename ${0})
wpa_dir="/etc/wpa_supplicant"
wpa_file="${wpa_dir}/wpa_supplicant.conf"
depend_list=("wpa_supplicant" "wpa_passphrase" "curl"
   	"dhclient" "iwlist" "cat" "pgrep" "pkill" "mkdir")

die()  { printf "${PROG_NAME}: $1\n" "${@}" 1>&2; exit 1; }
warn() { printf " - $1\n" "${@}" ; exit 1; }
msg()  { printf "$1\n" "${@}"; }
info() { printf "==> $1 \n" "${@}" ;}

usage ()
{
die "Usage: ${PROG_NAME} [OPTION]
if no option passed. script will running in background
	if already runned . will restart
	
Options:
  -h                : show this help page
  -i interface      : set network interface
  -l                : show wifi devices
  -n ssid=password  : make new configuration
  -k                : stopping the script
  -r                : runing script
  -s                : script status 
Examples:
  $ ${PROG_NAME} -i wlan0 -n tplink=12345678
  $ ${PROG_NAME} -i wlan0 -l"

}

change_config_file()
{
	ssid=$(msg $1 | cut -d= -f1)
	pass=$(msg $1 | cut -d= -f2)
	iface=$(msg $2)

	if [[ ! $iface ]] ;then
		warn "interface not set"
	fi

	if [[ ! $ssid ]] && [[ ! $pass ]] ; then
		warn "ssid or password not set ."
	fi

	if [[ $(wpa_passphrase $ssid $pass &>/dev/null ; msg $?) = 1 ]] ;then
		warn "ssid or password wrong ." 
	fi
	
	msg "# if you are using wpafi DONT EDIT THID FILE" > ${wpa_file}
	msg "# iface=${iface}" >> ${wpa_file}
	mkdir -p ${wpa_dir}
	wpa_passphrase ${ssid} ${pass} >> ${wpa_file}
	
	info "done"
}
list_wifi_devices()
{
	iface=$1
	
	info "wait..."
	iwlist $iface scanning | grep -E "Cell|ESSID|Encryption" --color=no
}
permit()
{
	[[ ${UID} != 0 ]] &&
		die "you need permision for this option : Permission denied"
}
off_wpafi()
{
	if [[ $(pgrep dhclient) ]] &&
		[[ $(pgrep wpa_supplicant) ]] ;then
		
		pkill dhclient
		pkill wpa_supplicant
		
		info "stopped"
	elif [[ ! $(pgrep dhclient) ]] &&
		[[  ! $(pgrep wpa_supplicant) ]] ;then
		info "already stopped"
	fi

}
status_wpafi()
{
	if [[ $(pgrep dhclient) && $(pgrep wpa_supplicant) ]] ;then
		info "wpafi status    : on"
	else
		info "wpafi status    : off"
	fi
}
internet_status()
{
	for (( i=0 ; i < 10 ; i++)) ;do
		stat_code=$(curl --connect-timeout 1.5 --location --silent --write-out '%{http_code}\n' "https://api.duckduckgo.com" -o /dev/null)
		if [[ ${stat_code} = "200" ]] ;then
			is_net_ok=true
			break
		fi
		sleep 1
	done

	if [[ ${is_net_ok} = true ]] ;then
		info "internet status : connected"
	else
		info "internat status : not connected"
	fi
}
run_wpafi()
{
	iface=$(cat ${wpa_file} | grep iface | cut -d'=' -f2)
	is_net_ok=false

	if [[ $(pgrep dhclient) && $(pgrep wpa_supplicant) ]] ;then
		die "wpafi status    : on"
	fi

	info "wait..."
	off_wpafi &>/dev/null
	wpa_supplicant -B -i${iface} -c /etc/wpa_supplicant/wpa_supplicant.conf &>/dev/null & 
	dhclient --no-pid wlan0 &>/dev/null &

	internet_status
	status_wpafi
}
check_depends()
{
	if [[ $(type $@ &>/dev/null; echo $?) = 0 ]]; then
		return 0 
	else 
		return 1
	fi
}

main()
{
	arg0=$1

	[[ ${arg0} = @(-h|--help) ]] &&
		usage
	if [[ ! ${arg0} ]] ;then
		permit
		run_wpafi
		exit 0
	fi

	while getopts "i:n:l:hrks" argv ;do
		case ${argv} in
			h)
				usage 
				;;
			r)
				permit 
				is_run_wpafi=true
				;;
			k)
				permit 
				is_off_wpafi=true
				;;
			n)
				permit
				is_change_config_file=true
				change_config_file_opt=${OPTARG}
				;;
			l)
				permit
				is_list_wifi_devices=true
				list_wifi_devices_opt=${OPTARG}
				;;
			s)
				permit
				is_status_wpafi=true
				;;
			i)
				permit
				is_iface=true
				is_iface_opt=${OPTARG}
				;;
			:)
				usage 
				;;
			?)
				usage
				;;
		esac
	done

	if [[ ${is_run_wpafi} ]] ;then
		run_wpafi 
		exit 0
	elif [[ ${is_off_wpafi} ]] ;then
		off_wpafi
		exit 0
	elif [[ ${is_status_wpafi} ]] ;then
		status_wpafi
		exit 0
	fi

	if [[ ${is_change_config_file} ]] && [[ ${is_iface} ]] ;then
		change_config_file ${change_config_file_opt} ${is_iface_opt}
		exit 0
	else
		usage
	fi
	if [[ ${is_list_wifi_devices} ]] && [[ ${is_iface} ]] ;then
		list_wifi_devices ${list_wifi_devices_opt} ${is_iface_opt}
		exit 0
	else
		usage
	fi

}

check_depends ${depend_list[@]} ||
	die "missing depends : \r\n\t ${depend_list[*]}"
main $@
